notifications:
  email: false
  slack:
    secure: tH8K3olmPKdkyyHebE8dkMpe1VqzyOLi60897aXTIDAG1f8cxq6wA8/RXFRMGjhu+b7EHVdSebvU3OvSzpR4fOFp9zyzbJqZx7TuO16ElJ6afUoqTGJ3G2i9w5e4kFTtlDnw8bCWfhpZiaZBIeQvg6hiJABI9OIzz7haU7FOwtr4mI8SlU4yIumE/J7czDQCWD3VYnarZKmj/tgU4pBwCMitYNWNgjs69cEk1Y++f8pWD8GPiL2Nngs4L/DBdCd8tG2PInqdDGtn+ZldUodi1tS/syRfYqA8oVNgXdYU2zevNGfM1ro6jlN6kxor+itLm0rMaV4ZdMGOONz/O8RZu6zstisyihYPgo9c3gT3rXPxXBZwOkKWUWRkUKFDqoRRU1nT7fTQwbezBMiS04Q8Xstm0UyMLm0nxwTjZ79vr6Pe8uSplU5wie+3RzVzWcig+53z+Sv8XWIKdtBlYPbYMBmYIK1LSysQC1ZCtp/zLLH+VF1UdhwK+h1YDUvfFUhX9JBpgRkB00xwnCJiTLwLJWoiv5EY/HfWIuwUrL9Hln/4maqhkH0OUKcuNjQARx14vszENVH+g49cyNjG59/cp/zEd6i3Az/twYwjt2xEADxQFv4tie/TlgvhvGqkdLbOTM5ksRh9ADs052gzub/DXbkuMEp+o4y1DOCSqm4sO5g=
language: node_js
node_js:
- stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
