notifications:
  email: false
  slack: tnw-dev-labs:d6yH72Mt57B6LOG312LnRwHW

language: node_js
node_js:
  - stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
